In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv


In [2]:
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("/kaggle/input/digit-recognizer/train.csv")

In [4]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [5]:
data = np.array(data)

In [6]:
data


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]])

In [7]:
m , n = data.shape

In [8]:
np.random.shuffle(data)
m, n

(42000, 785)

In [9]:
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [10]:
X_train = X_train / 255.0
X_dev = X_dev / 255.0

In [11]:
Y_dev

array([8, 3, 9, 0, 5, 6, 4, 1, 9, 4, 3, 7, 1, 9, 3, 9, 9, 7, 7, 9, 3, 5,
       4, 3, 8, 0, 8, 0, 5, 6, 7, 5, 4, 0, 9, 9, 9, 0, 3, 7, 8, 1, 6, 1,
       6, 0, 4, 3, 5, 1, 4, 9, 4, 7, 1, 4, 6, 9, 9, 9, 0, 2, 8, 6, 2, 0,
       6, 8, 2, 2, 4, 6, 9, 3, 8, 7, 8, 3, 7, 1, 5, 2, 3, 2, 6, 1, 8, 5,
       2, 6, 9, 1, 9, 8, 3, 8, 3, 6, 0, 5, 8, 9, 4, 2, 9, 6, 4, 4, 3, 3,
       7, 7, 4, 8, 8, 9, 2, 0, 0, 3, 2, 0, 8, 7, 6, 4, 0, 5, 8, 3, 8, 0,
       1, 8, 5, 3, 0, 3, 9, 9, 9, 2, 7, 9, 5, 2, 0, 6, 1, 7, 9, 1, 0, 4,
       0, 9, 5, 6, 3, 0, 7, 0, 1, 2, 2, 5, 4, 3, 1, 6, 5, 0, 6, 4, 5, 1,
       3, 3, 5, 4, 7, 4, 3, 0, 0, 5, 2, 3, 1, 9, 1, 6, 6, 1, 1, 2, 0, 3,
       1, 0, 0, 7, 6, 5, 5, 1, 6, 0, 4, 3, 0, 2, 7, 8, 9, 5, 0, 2, 0, 0,
       8, 1, 1, 3, 5, 1, 3, 2, 9, 2, 2, 2, 3, 5, 8, 9, 2, 5, 9, 7, 5, 9,
       1, 2, 2, 8, 6, 3, 3, 4, 2, 8, 8, 1, 9, 6, 4, 1, 2, 5, 2, 0, 4, 0,
       7, 3, 1, 3, 8, 0, 6, 1, 5, 7, 7, 8, 4, 6, 1, 1, 0, 6, 0, 7, 7, 7,
       3, 4, 3, 4, 2, 9, 9, 8, 9, 0, 0, 7, 9, 8, 0,

In [12]:
X_dev.shape

(784, 1000)

In [13]:
Y_train

array([9, 7, 4, ..., 8, 4, 3])

In [14]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
def init_params():
    W1 = np.random.randn(128, 784) * np.sqrt(2. / 784)
    b1 = np.zeros((128, 1))
    W2 = np.random.randn(10, 128) * np.sqrt(2. / 10)
    b2 = np.zeros((10, 1))
    return W1, b1, W2, b2
    
def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    expZ = np.exp(Z - np.max(Z, axis=0, keepdims=True))
    return expZ / (np.sum(expZ, axis=0, keepdims=True) + 1e-8)

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2


def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return (Z > 0).astype(float)

def back_prop(Z1, A1, Z2, A2, W2,X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2, 1, keepdims=True)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, 1, keepdims=True)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def get_predictions(A2):
    return np.argmax(A2, 0)

In [16]:
def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range (iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration:", i)
            print("Accuracy:", get_accuracy(get_predictions(A2), Y))
            loss = -np.sum(one_hot(Y) * np.log(A2 + 1e-8)) / m
            print("Loss:", loss)

    return W1, b1, W2, b2



In [17]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.01)

Iteration: 0
[3 8 8 ... 9 8 3] [9 7 4 ... 8 4 3]
Accuracy: 0.12697560975609756
Loss: 2.754501520443397
Iteration: 10
[3 8 8 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.37490243902439024
Loss: 1.8011045510835195
Iteration: 20
[3 8 8 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.547439024390244
Loss: 1.391828807286846
Iteration: 30
[3 8 8 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.6409268292682927
Loss: 1.1553967406764627
Iteration: 40
[3 8 8 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.6969512195121951
Loss: 1.0025087440953842
Iteration: 50
[3 1 8 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.7323170731707317
Loss: 0.8957823693821556
Iteration: 60
[9 1 4 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.7582682926829268
Loss: 0.8170540763868933
Iteration: 70
[9 1 4 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.7773170731707317
Loss: 0.7565513345578118
Iteration: 80
[9 1 4 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.7930487804878049
Loss: 0.7085751427020058
Iteration: 90
[9 1 4 ... 5 4 3] [9 7 4 ... 8 4 3]
Accuracy: 0.8045

In [18]:
np.savez('/kaggle/working/my_model_weights.npz', W1=W1, b1=b1, W2=W2, b2=b2)